import { displayText } from './attributeTypes'

// Field attribute types per the PIQI Clinical Data Model, needed so patient
// assertions and manual entry wrap values in the right shape (Simple string
// vs. { text, codings } CodeableConcept, etc).
export const ATTRIBUTE_TYPES = {
  demographics: {
    firstName: 'simple',
    lastName: 'simple',
    middleName: 'simple',
    birthDate: 'simple',
    birthSex: 'cc',
    genderIdentity: 'cc',
    race: 'cc',
    ethnicity: 'cc',
    maritalStatus: 'cc',
    primaryLanguage: 'cc',
    deathDate: 'simple',
    deceased: 'cc',
    patientIdentifier: 'simple',
    currentAddress: 'simple',
    emailAddress: 'simple',
    telecom: 'simple',
  },
  allergies: {
    substance: 'cc',
    category: 'cc',
    reaction: 'cc',
    severity: 'cc',
    effectiveDate: 'simple',
    clinicalStatus: 'cc',
    verificationStatus: 'cc',
  },
  conditions: {
    condition: 'cc',
    onsetDate: 'simple',
    conditionStatus: 'cc',
    resolutionDate: 'simple',
    clinicalStatus: 'cc',
    verificationStatus: 'cc',
    conditionCategory: 'cc',
    assertedDate: 'simple',
    recordedDate: 'simple',
  },
  immunizations: {
    administrationDate: 'simple',
    immunization: 'cc',
    lotNumber: 'simple',
    reaction: 'cc',
    expirationDate: 'simple',
    immunizationStatus: 'cc',
    immunizationStatusReason: 'cc',
    primarySource: 'simple',
  },
  labResults: {
    order: 'cc',
    test: 'cc',
    resultUnit: 'cc',
    resultValue: 'obsval',
    interpretation: 'cc',
    specimenType: 'cc',
    resultStatus: 'cc',
    performedDateTime: 'simple',
    issuedDateTime: 'simple',
    referenceRange: 'rangeval',
    performingSite: 'cc',
    specimenIdentifier: 'simple',
    orderDate: 'simple',
    labCategory: 'cc',
  },
  medications: {
    medication: 'cc',
    doseAmount: 'simple',
    doseAmountUnit: 'cc',
    doseRoute: 'cc',
    doseQuantity: 'simple',
    doseQuantityUnit: 'cc',
    instructions: 'simple',
    indication: 'cc',
    startDate: 'simple',
    endDate: 'simple',
    statementDate: 'simple',
    adherence: 'cc',
    fillStatus: 'cc',
    requestStatus: 'cc',
    medicationCategory: 'cc',
    medicationIntent: 'cc',
  },
  procedures: {
    procedureDateTime: 'simple',
    procedure: 'cc',
    procedureReason: 'cc',
    procedureStatus: 'cc',
    procedurePerformedDate: 'simple',
  },
  vitalSigns: {
    vitalSign: 'cc',
    resultValue: 'obsval',
    resultUnit: 'cc',
    interpretation: 'cc',
    resultStatus: 'cc',
    performedDateTime: 'simple',
    performingSite: 'cc',
    referenceRange: 'rangeval',
    issuedDateTime: 'simple',
    vitalSignCategory: 'cc',
  },
  medicalDevices: {
    deviceID: 'simple',
    deviceType: 'cc',
    implantationDate: 'simple',
    deviceStatus: 'cc',
    serialNumber: 'simple',
    lotNumber: 'simple',
    expirationDate: 'simple',
    manufactureDate: 'simple',
  },
  healthAssessments: {
    assessment: 'cc',
    assessmentStatus: 'cc',
    resultValue: 'obsval',
    resultUnit: 'cc',
    effectiveDate: 'simple',
    issueDateTime: 'simple',
    category: 'cc',
  },
}

// The subset of each class's attributes checked for completeness -- the full
// PIQI model has more optional attributes than are useful to flag as
// "missing" for a patient-facing readiness check.
export const REQUIRED_FIELDS = {
  demographics: ['firstName', 'lastName', 'birthDate', 'birthSex'],
  allergies: ['substance', 'reaction', 'severity'],
  conditions: ['condition', 'conditionStatus'],
  immunizations: ['immunization', 'administrationDate'],
  labResults: ['test', 'resultValue', 'resultUnit', 'performedDateTime'],
  medications: ['medication', 'doseAmount', 'doseRoute', 'requestStatus'],
  procedures: ['procedure', 'procedureDateTime', 'procedureStatus'],
  vitalSigns: ['vitalSign', 'resultValue', 'performedDateTime'],
  medicalDevices: ['deviceType', 'deviceStatus'],
  healthAssessments: ['assessment', 'resultValue', 'effectiveDate'],
}

export const FIELD_LABELS = {
  firstName: 'first name',
  lastName: 'last name',
  middleName: 'middle name',
  birthDate: 'date of birth',
  birthSex: 'birth sex',
  genderIdentity: 'gender identity',
  race: 'race',
  ethnicity: 'ethnicity',
  maritalStatus: 'marital status',
  primaryLanguage: 'primary language',
  deathDate: 'death date',
  deceased: 'deceased',
  patientIdentifier: 'patient identifier',
  currentAddress: 'address',
  emailAddress: 'email address',
  telecom: 'phone',
  substance: 'substance',
  category: 'category',
  reaction: 'reaction',
  severity: 'severity',
  effectiveDate: 'effective date',
  clinicalStatus: 'clinical status',
  verificationStatus: 'verification status',
  condition: 'condition',
  onsetDate: 'onset date',
  conditionStatus: 'condition status',
  resolutionDate: 'resolution date',
  conditionCategory: 'condition category',
  assertedDate: 'asserted date',
  recordedDate: 'recorded date',
  administrationDate: 'administration date',
  immunization: 'immunization',
  lotNumber: 'lot number',
  expirationDate: 'expiration date',
  immunizationStatus: 'immunization status',
  immunizationStatusReason: 'status reason',
  primarySource: 'primary source',
  order: 'order',
  test: 'test',
  resultUnit: 'result unit',
  resultValue: 'result value',
  interpretation: 'interpretation',
  specimenType: 'specimen type',
  resultStatus: 'result status',
  performedDateTime: 'performed date',
  issuedDateTime: 'issued date',
  referenceRange: 'reference range',
  performingSite: 'performing site',
  specimenIdentifier: 'specimen identifier',
  orderDate: 'order date',
  labCategory: 'category',
  medication: 'medication',
  doseAmount: 'dose amount',
  doseAmountUnit: 'dose amount unit',
  doseRoute: 'route',
  doseQuantity: 'dose quantity',
  doseQuantityUnit: 'dose quantity unit',
  instructions: 'instructions',
  indication: 'indication',
  startDate: 'start date',
  endDate: 'end date',
  statementDate: 'statement date',
  adherence: 'adherence',
  fillStatus: 'fill status',
  requestStatus: 'status',
  medicationCategory: 'medication category',
  medicationIntent: 'intent',
  procedureDateTime: 'procedure date',
  procedure: 'procedure',
  procedureReason: 'reason',
  procedureStatus: 'status',
  procedurePerformedDate: 'performed date',
  vitalSign: 'vital sign',
  vitalSignCategory: 'category',
  deviceID: 'device ID',
  deviceType: 'device type',
  implantationDate: 'implantation date',
  deviceStatus: 'status',
  serialNumber: 'serial number',
  manufactureDate: 'manufacture date',
  assessment: 'assessment',
  assessmentStatus: 'status',
}

export const IDENTITY_FIELDS = {
  allergies: 'substance',
  conditions: 'condition',
  immunizations: 'immunization',
  labResults: 'test',
  medications: 'medication',
  procedures: 'procedure',
  vitalSigns: 'vitalSign',
  medicalDevices: 'deviceType',
  healthAssessments: 'assessment',
}

export const DATE_FIELDS = {
  allergies: 'effectiveDate',
  conditions: 'onsetDate',
  immunizations: 'administrationDate',
  labResults: 'performedDateTime',
  medications: 'startDate',
  procedures: 'procedureDateTime',
  vitalSigns: 'performedDateTime',
  medicalDevices: 'implantationDate',
  healthAssessments: 'effectiveDate',
}

export function recordLabel(domain, data) {
  if (domain === 'demographics') {
    const name = [displayText(data.firstName), displayText(data.lastName)].filter(Boolean).join(' ')
    return name || 'Untitled record'
  }
  if (domain === 'coverage') {
    return data.plan_name || 'Untitled record'
  }
  const field = IDENTITY_FIELDS[domain]
  return (field && displayText(data[field])) || 'Untitled record'
}

export function normalizeText(value) {
  return (displayText(value) ?? '').toString().trim().toLowerCase()
}
