// Field types for the PIQI Patient EOB (claims) model, PAT_EOB_V1, which is based
// on CPCDS. Generated from the model definition in the PIQI reference application:
// https://github.com/piqiframework/reference_application/blob/main/PIQI_Engine.Server/ReferenceData/Models/PAT_EOB_V1.json

export const CLAIMS_ATTRIBUTE_TYPES = {
  member: {
    memberId: 'simple',
    uniqueMemberId: 'simple',
    memberIdentifierType: 'cc',
    dateOfBirth: 'simple',
    dateOfDeath: 'simple',
    deceasedFlag: 'simple',
    birthSex: 'cc',
    raceCode: 'cc',
    ethnicity: 'cc',
    city: 'simple',
    county: 'simple',
    state: 'simple',
    country: 'simple',
    postalCode: 'simple',
    addressStartDate: 'simple',
    addressEndDate: 'simple',
    telecomSystem: 'cc',
    telecomUse: 'cc',
    streetAddress: 'simple',
    primaryLanguage: 'cc',
  },
  coverage: {
    subscriberId: 'simple',
    coverageType: 'cc',
    coverageStatus: 'cc',
    startDate: 'simple',
    endDate: 'simple',
    groupId: 'simple',
    groupName: 'simple',
    planIdentifier: 'simple',
    planName: 'simple',
    payerIdentifier: 'simple',
    otherPayerName: 'simple',
    relationshipToSubscriber: 'cc',
    claimPayerName: 'simple',
  },
  medicalClaim: {
    claimDrgVersion: 'simple',
    claimDrgCode: 'cc',
    claimStartDate: 'simple',
    statementThruDate: 'simple',
    procedureCodeType: 'cc',
    adjudicationDate: 'simple',
    dischargedate: 'simple',
    primaryPayerIdentifier: 'cc',
    claimSubType: 'cc',
    patientDischargeStatusCode: 'cc',
    claimPayerIdentifier: 'simple',
    medicalRecordNumber: 'simple',
    claimIdentifierType: 'simple',
    processingStatusCode: 'cc',
    billFacilityTypeCode: 'cc',
    claimAdjustedfromIdentifier: 'simple',
    claimAdjustedtoIdentifier: 'simple',
    claimAdjustedRelationship: 'cc',
    claimReceivedDate: 'simple',
    claimPaymentStatusCode: 'cc',
    claimPaidDate: 'simple',
    claimDiscountAmount: 'simple',
    serviceClassificationTypeCode: 'cc',
    patientAccountNumber: 'simple',
    claimPayeeTypeCode: 'cc',
    inpatientSourceAdmissionCode: 'cc',
    admissionDate: 'simple',
    paymentDenialCode: 'cc',
    claimServiceEndDate: 'simple',
    claimTypeCode: 'cc',
    payerClaimUniqueIdentifier: 'simple',
    adjudicationAmountType: 'cc',
    inpatientAdmissionTypeCode: 'cc',
    frequencyCode: 'cc',
    claimPayee: 'simple',
    totalAmount: 'simple',
    statementFromDate: 'simple',
    claimTotalSubmittedAmount: 'simple',
    claimTotalAllowedAmount: 'simple',
    amountPaidByPatient: 'simple',
    claimAmountPaidToProvider: 'simple',
    memberReimbursement: 'simple',
    claimPaymentAmount: 'simple',
    claimNonCoveredAmount: 'simple',
    memberPaidDeductible: 'simple',
    coInsuranceLiabilityAmount: 'simple',
    copayAmount: 'simple',
    memberLiability: 'simple',
    claimOtherPayerPaidAmount: 'simple',
    claimUse: 'cc',
    claimLastUpdateDate: 'simple',
  },
  claimServiceLine: {
    serviceDate: 'simple',
    lineNumber: 'simple',
    serviceToDate: 'simple',
    typeOfService: 'cc',
    placeOfServiceCode: 'cc',
    revenueCenterCode: 'cc',
    allowedNumberOfUnits: 'simple',
    nationalDrugCode: 'cc',
    compoundCode: 'cc',
    quantityDispensed: 'simple',
    quantityQualifierCode: 'cc',
    benefitPaymentStatus: 'cc',
    linePaymentDenialCode: 'cc',
    paymentMemberExplanation: 'simple',
    lineNoncoveredAmount: 'simple',
    lineMemberReimbursement: 'simple',
    linePaymentAmount: 'simple',
    lineDiscountAmount: 'simple',
    lineAmountPaidByPatient: 'simple',
    drugCost: 'simple',
    lineAllowedAmount: 'simple',
    lineAmountPaidToProvider: 'simple',
    linePatientDeductible: 'simple',
    lineOtherPayerPaidAmount: 'simple',
    lineCoinsuranceAmount: 'simple',
    lineSubmittedAmount: 'simple',
    lineMemberLiabilityAmount: 'simple',
    lineCopayAmount: 'simple',
    lineProcedureCode: 'cc',
    lineProcedureCodeModifier: 'cc',
  },
  claimDiagnosis: {
    diagnosisCode: 'cc',
    eCodeIndicator: 'simple',
    presentOnAdmissionIndicator: 'simple',
    diagnosisType: 'cc',
  },
  claimProcedure: {
    procedureClaimLine: 'simple',
    procedureCode: 'cc',
    procedureDate: 'simple',
    procedureType: 'cc',
    modifierCode1: 'cc',
    modifierCode2: 'cc',
    modifierCode3: 'cc',
    modifierCode4: 'cc',
  },
  pharmacyClaim: {
    daysSupply: 'simple',
    rxServiceReferenceNumber: 'simple',
    dawCode: 'simple',
    refillNumber: 'simple',
    prescriptionOriginCode: 'simple',
    planReportedBrandGenericCode: 'cc',
    totalAmount: 'simple',
    claimIdentifierAmount: 'simple',
    adjudicationAmountType: 'simple',
  },
  dentalClaim: {
    procedureCode: 'cc',
    procedureModifierCode: 'cc',
    toothNumberFirstOccurrence: 'cc',
    toothSurface: 'cc',
    missingToothNumberFirstOccurrence: 'cc',
    orthodonticsTreatmentIndicator: 'simple',
    orthodonticsApplianceApplicationDate: 'simple',
    totalNumberOfMonthsForOrthodontia: 'simple',
    prosthesisReplacementIndicator: 'simple',
    dateOfPriorProsthesisPlacement: 'simple',
    toothNumberAfterFirstOccurrence: 'cc',
    missingToothNumberAfterFirstOccurrence: 'cc',
  },
  provider: {
    providerNpi: 'simple',
    providerContractingStatus: 'cc',
    siteOfServiceNetworkStatus: 'cc',
    careTeamRole: 'cc',
    providerName: 'simple',
    providerAddress: 'simple',
    providerPayerSpecificIdentifier: 'cc',
    providerType: 'cc',
  },
}

// Classes in the order the PIQI sample claims messages use.
export const CLAIMS_CLASS_ORDER = ['member', 'coverage', 'medicalClaim', 'provider', 'claimDiagnosis', 'claimProcedure', 'claimServiceLine', 'pharmacyClaim', 'dentalClaim']

// Class field names that only exist in the claims model (`coverage` is also an
// M5 Health record type, so it is not listed here).
export const CLAIMS_ONLY_CLASSES = new Set(['medicalClaim', 'claimDiagnosis', 'claimProcedure', 'claimServiceLine', 'pharmacyClaim', 'dentalClaim', 'member', 'provider'])

export const CLAIMS_FIELD_LABELS = {
  memberId: "Member ID",
  uniqueMemberId: "Unique Member ID",
  memberIdentifierType: "Member Identifier Type",
  dateOfBirth: "Date of Birth",
  dateOfDeath: "Date of Death",
  deceasedFlag: "Deceased Flag",
  birthSex: "Birth Sex",
  raceCode: "Race Code",
  ethnicity: "Ethnicity",
  city: "City",
  county: "County",
  state: "State",
  country: "Country",
  postalCode: "Postal Code",
  addressStartDate: "Address start date",
  addressEndDate: "Address end date",
  telecomSystem: "member telecom system",
  telecomUse: "telecom use",
  streetAddress: "Street address",
  primaryLanguage: "primary language",
  subscriberId: "Subscriber ID",
  coverageType: "Coverage Type",
  coverageStatus: "Coverage Status",
  startDate: "Start Date",
  endDate: "End Date",
  groupId: "Group ID",
  groupName: "Group Name",
  planIdentifier: "Plan Identifier",
  planName: "Plan Name",
  payerIdentifier: "Payer Identifier",
  otherPayerName: "Other Payer Name",
  relationshipToSubscriber: "Relationship to Subscriber",
  claimPayerName: "Claim payer Name",
  claimDrgVersion: "Claim DRG Version",
  claimDrgCode: "DRG code",
  claimStartDate: "Claim start date",
  statementThruDate: "Statement Thru Date",
  procedureCodeType: "Procedure Code Type",
  adjudicationDate: "Adjudication Date",
  dischargedate: "Discharge Date",
  primaryPayerIdentifier: "Primary Payer Identifier",
  claimSubType: "Claim Sub Type",
  patientDischargeStatusCode: "Patient Discharge Status Code",
  claimPayerIdentifier: "Claim Payer Identifier",
  medicalRecordNumber: "Medical Record Number",
  claimIdentifierType: "Claim Identifier Type",
  processingStatusCode: "Processing Status Code",
  billFacilityTypeCode: "Bill Facility Type Code",
  claimAdjustedfromIdentifier: "Claim Adjusted from Identifier",
  claimAdjustedtoIdentifier: "Claim Adjusted to Identifier",
  claimAdjustedRelationship: "claim adjusted relationship ",
  claimReceivedDate: "Claim Received Date",
  claimPaymentStatusCode: "Payment Status Code",
  claimPaidDate: "Claim Paid Date",
  claimDiscountAmount: "Claim Discount Amount",
  serviceClassificationTypeCode: "Service Classification Type Code",
  patientAccountNumber: "Patient Account Number",
  claimPayeeTypeCode: "Claim Payee Type Code",
  inpatientSourceAdmissionCode: "Inpatient Source admin Code",
  admissionDate: "Admission Date",
  paymentDenialCode: "Payment Denial Code",
  claimServiceEndDate: "Claim  End Date",
  claimTypeCode: "Claim Type Code",
  payerClaimUniqueIdentifier: "Claim Unique Identifier",
  adjudicationAmountType: "Adj Amount Type",
  inpatientAdmissionTypeCode: "Inpatient Admin Type Code",
  frequencyCode: "Frequency Code",
  claimPayee: "Claim Payee ",
  totalAmount: "Total Amount",
  statementFromDate: "Statement From Date",
  claimTotalSubmittedAmount: "total submitted amount",
  claimTotalAllowedAmount: "total allowed amount",
  amountPaidByPatient: "Amount Paid by Patient",
  claimAmountPaidToProvider: "Claim Amount Paid to Provider",
  memberReimbursement: "Member Reimbursement",
  claimPaymentAmount: "Claim Payment Amount",
  claimNonCoveredAmount: "Claim Non-covered Amount",
  memberPaidDeductible: "Member Paid Deductible",
  coInsuranceLiabilityAmount: "Co-insurance Liability Amount",
  copayAmount: "Copay Amount",
  memberLiability: "Member Liability",
  claimOtherPayerPaidAmount: "Claim Other Payer Paid Amount",
  claimUse: "Claim Use",
  claimLastUpdateDate: "last update date",
  serviceDate: "Service Date",
  lineNumber: "Line Number",
  serviceToDate: "Service to Date",
  typeOfService: "Type of Service",
  placeOfServiceCode: "Place of Service Code",
  revenueCenterCode: "Revenue Center Code",
  allowedNumberOfUnits: "Allowed Number of Units",
  nationalDrugCode: "National Drug Code",
  compoundCode: "Compound Code",
  quantityDispensed: "Quantity Dispensed",
  quantityQualifierCode: "Quantity Qualifier Code",
  benefitPaymentStatus: "Benefit Payment Status",
  linePaymentDenialCode: "Line Payment Denial Code",
  paymentMemberExplanation: "Payment member explanation",
  lineNoncoveredAmount: "Line Noncovered Amount",
  lineMemberReimbursement: "Line Member Reimbursement",
  linePaymentAmount: "Line Payment Amount",
  lineDiscountAmount: "Line Discount Amount",
  lineAmountPaidByPatient: "Line Amount Paid by Patient",
  drugCost: "Drug Cost",
  lineAllowedAmount: "Line Allowed Amount",
  lineAmountPaidToProvider: "Line Amount Paid to Provider",
  linePatientDeductible: "Line Patient Deductible",
  lineOtherPayerPaidAmount: "Line Other Payer Paid Amount",
  lineCoinsuranceAmount: "Line Coinsurance Amount",
  lineSubmittedAmount: "Line Submitted Amount",
  lineMemberLiabilityAmount: "Line Member Liability",
  lineCopayAmount: "Line Copay Amount",
  lineProcedureCode: "line procedure code",
  lineProcedureCodeModifier: "line procedure code modifier",
  diagnosisCode: "Diagnosis Code",
  eCodeIndicator: "Is E code",
  presentOnAdmissionIndicator: "Present on Admission",
  diagnosisType: "Diagnosis Type",
  procedureClaimLine: "Procedure Line",
  procedureCode: "Procedure Code ",
  procedureDate: "Procedure Date",
  procedureType: "Procedure Type",
  modifierCode1: "Modifier Code -1",
  modifierCode2: "Modifier Code -2",
  modifierCode3: "Modifier Code -3",
  modifierCode4: "Modifier Code -4",
  daysSupply: "Days Supply",
  rxServiceReferenceNumber: "RX Service Ref No",
  dawCode: "DAW Code",
  refillNumber: "Refill Number",
  prescriptionOriginCode: "Presc Origin Code",
  planReportedBrandGenericCode: "Plan Brand-Generic Code",
  claimIdentifierAmount: "Claim Identifier Amount",
  procedureModifierCode: "Procedure Modifier Code ",
  toothNumberFirstOccurrence: "Tooth No - First Occ",
  toothSurface: "Tooth Surface",
  missingToothNumberFirstOccurrence: "Missing Tooth Number - First Occurrence",
  orthodonticsTreatmentIndicator: "Orthodontics Treatment Indicator",
  orthodonticsApplianceApplicationDate: "Orthodontics Appliance Application Date",
  totalNumberOfMonthsForOrthodontia: "Total Number of Months for Orthodontia",
  prosthesisReplacementIndicator: "Prosthesis Replacement Indicator",
  dateOfPriorProsthesisPlacement: "Date of Prior Prosthesis Placement",
  toothNumberAfterFirstOccurrence: "Tooth Number - After First Occurrence",
  missingToothNumberAfterFirstOccurrence: "Missing Tooth Number - After First Occurrence",
  providerNpi: "Provider NPI",
  providerContractingStatus: "Provider Contracting Status",
  siteOfServiceNetworkStatus: "Site of Service Network Status",
  careTeamRole: "Care Team Role",
  providerName: "Provider Name",
  providerAddress: "Provider Address",
  providerPayerSpecificIdentifier: "Provider Payer Specific Identifier",
  providerType: "Provider Type",
}

// Field that best names one record of each claims class, for check titles.
export const CLAIMS_IDENTITY_FIELDS = {
  medicalClaim: 'payerClaimUniqueIdentifier',
  claimDiagnosis: 'diagnosisCode',
  claimProcedure: 'procedureCode',
  claimServiceLine: 'lineNumber',
  provider: 'providerNpi',
  coverage: 'planName',
  member: 'memberId',
}

// The Gateway reports the class name; accept either "Medical Claim" or
// "medicalClaim" style and return the message field name.
const CLASS_KEYS = Object.fromEntries(
  Object.keys(CLAIMS_ATTRIBUTE_TYPES).map((k) => [k.toLowerCase(), k]),
)

export function claimsClassKey(className) {
  return CLASS_KEYS[String(className ?? '').replace(/[^a-z]/gi, '').toLowerCase()]
}
